 type Card {
    suit: String!
    value: String!
    code: String!
    image: String
  }

  enum PlayerRole {
    dealer
    small_blind
    big_blind
    regular
  }

  type Player {
    id: ID!
    name: String!
    hand: [Card!]!
    role: PlayerRole
    bet: Int
    wallet: Int!
    hasTurn: Boolean
  }

  type Round {
    players: [Player!]!
    bigBlind: Int!
    pot: Int!
    communityCards: [Card!]!
    turn: Turn
    winners: [Player!]
  }

  type PokerGame {
    players: [Player!]!
    pot: Int!
    bigBlind: Int!
    bustedPlayers: [Player!]!
    currentRound: Round
  }

  type Turn {
    id: ID!
    player: Player!
    bet: Int!
  }

  input CardInput {
    suit: String!
    value: String!
    code: String!
    image: String
  }

  input PlayerInput {
    id: ID!
    name: String!
    hand: [CardInput!]!
    role: PlayerRole
    bet: Int
    wallet: Int!
    hasTurn: Boolean
  }

  type Query {
    newDeck: [Card!]!
  }

  type Mutation {
    drawCards(count: Int!): [Card!]!
    newGame(players: [PlayerInput!]!, bigBlind: Int): PokerGame!
  }